// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/aerodocs/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from Agent → Hub
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Register
	//	*AgentMessage_FileListResponse
	//	*AgentMessage_LogStreamChunk
	//	*AgentMessage_FileUploadAck
	//	*AgentMessage_FileReadResponse
	//	*AgentMessage_FileDeleteResponse
	//	*AgentMessage_UnregisterAck
	//	*AgentMessage_CertRenewRequest
	//	*AgentMessage_TerminalOpenAck
	//	*AgentMessage_TerminalData
	//	*AgentMessage_TerminalExit
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterAgent {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetFileListResponse() *FileListResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileListResponse); ok {
			return x.FileListResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetLogStreamChunk() *LogStreamChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_LogStreamChunk); ok {
			return x.LogStreamChunk
		}
	}
	return nil
}

func (x *AgentMessage) GetFileUploadAck() *FileUploadAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileUploadAck); ok {
			return x.FileUploadAck
		}
	}
	return nil
}

func (x *AgentMessage) GetFileReadResponse() *FileReadResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileReadResponse); ok {
			return x.FileReadResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetFileDeleteResponse() *FileDeleteResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_FileDeleteResponse); ok {
			return x.FileDeleteResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetUnregisterAck() *UnregisterAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_UnregisterAck); ok {
			return x.UnregisterAck
		}
	}
	return nil
}

func (x *AgentMessage) GetCertRenewRequest() *CertRenewRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CertRenewRequest); ok {
			return x.CertRenewRequest
		}
	}
	return nil
}

func (x *AgentMessage) GetTerminalOpenAck() *TerminalOpenAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TerminalOpenAck); ok {
			return x.TerminalOpenAck
		}
	}
	return nil
}

func (x *AgentMessage) GetTerminalData() *TerminalData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TerminalData); ok {
			return x.TerminalData
		}
	}
	return nil
}

func (x *AgentMessage) GetTerminalExit() *TerminalExit {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TerminalExit); ok {
			return x.TerminalExit
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Register struct {
	Register *RegisterAgent `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type AgentMessage_FileListResponse struct {
	// Stubs for sub-projects 4-6
	FileListResponse *FileListResponse `protobuf:"bytes,10,opt,name=file_list_response,json=fileListResponse,proto3,oneof"`
}

type AgentMessage_LogStreamChunk struct {
	LogStreamChunk *LogStreamChunk `protobuf:"bytes,11,opt,name=log_stream_chunk,json=logStreamChunk,proto3,oneof"`
}

type AgentMessage_FileUploadAck struct {
	FileUploadAck *FileUploadAck `protobuf:"bytes,12,opt,name=file_upload_ack,json=fileUploadAck,proto3,oneof"`
}

type AgentMessage_FileReadResponse struct {
	FileReadResponse *FileReadResponse `protobuf:"bytes,13,opt,name=file_read_response,json=fileReadResponse,proto3,oneof"`
}

type AgentMessage_FileDeleteResponse struct {
	FileDeleteResponse *FileDeleteResponse `protobuf:"bytes,15,opt,name=file_delete_response,json=fileDeleteResponse,proto3,oneof"`
}

type AgentMessage_UnregisterAck struct {
	UnregisterAck *UnregisterAck `protobuf:"bytes,16,opt,name=unregister_ack,json=unregisterAck,proto3,oneof"`
}

type AgentMessage_CertRenewRequest struct {
	CertRenewRequest *CertRenewRequest `protobuf:"bytes,17,opt,name=cert_renew_request,json=certRenewRequest,proto3,oneof"`
}

type AgentMessage_TerminalOpenAck struct {
	TerminalOpenAck *TerminalOpenAck `protobuf:"bytes,18,opt,name=terminal_open_ack,json=terminalOpenAck,proto3,oneof"`
}

type AgentMessage_TerminalData struct {
	TerminalData *TerminalData `protobuf:"bytes,19,opt,name=terminal_data,json=terminalData,proto3,oneof"`
}

type AgentMessage_TerminalExit struct {
	TerminalExit *TerminalExit `protobuf:"bytes,20,opt,name=terminal_exit,json=terminalExit,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_FileListResponse) isAgentMessage_Payload() {}

func (*AgentMessage_LogStreamChunk) isAgentMessage_Payload() {}

func (*AgentMessage_FileUploadAck) isAgentMessage_Payload() {}

func (*AgentMessage_FileReadResponse) isAgentMessage_Payload() {}

func (*AgentMessage_FileDeleteResponse) isAgentMessage_Payload() {}

func (*AgentMessage_UnregisterAck) isAgentMessage_Payload() {}

func (*AgentMessage_CertRenewRequest) isAgentMessage_Payload() {}

func (*AgentMessage_TerminalOpenAck) isAgentMessage_Payload() {}

func (*AgentMessage_TerminalData) isAgentMessage_Payload() {}

func (*AgentMessage_TerminalExit) isAgentMessage_Payload() {}

// Messages from Hub → Agent
type HubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HubMessage_HeartbeatAck
	//	*HubMessage_RegisterAck
	//	*HubMessage_FileListRequest
	//	*HubMessage_LogStreamRequest
	//	*HubMessage_FileUploadRequest
	//	*HubMessage_FileReadRequest
	//	*HubMessage_LogStreamStop
	//	*HubMessage_FileDeleteRequest
	//	*HubMessage_UnregisterRequest
	//	*HubMessage_CertRenewResponse
	//	*HubMessage_TerminalOpenRequest
	//	*HubMessage_TerminalInput
	//	*HubMessage_TerminalResize
	//	*HubMessage_TerminalClose
	Payload       isHubMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HubMessage) GetPayload() isHubMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HubMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *HubMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *HubMessage) GetFileListRequest() *FileListRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_FileListRequest); ok {
			return x.FileListRequest
		}
	}
	return nil
}

func (x *HubMessage) GetLogStreamRequest() *LogStreamRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_LogStreamRequest); ok {
			return x.LogStreamRequest
		}
	}
	return nil
}

func (x *HubMessage) GetFileUploadRequest() *FileUploadRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_FileUploadRequest); ok {
			return x.FileUploadRequest
		}
	}
	return nil
}

func (x *HubMessage) GetFileReadRequest() *FileReadRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_FileReadRequest); ok {
			return x.FileReadRequest
		}
	}
	return nil
}

func (x *HubMessage) GetLogStreamStop() *LogStreamStop {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_LogStreamStop); ok {
			return x.LogStreamStop
		}
	}
	return nil
}

func (x *HubMessage) GetFileDeleteRequest() *FileDeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_FileDeleteRequest); ok {
			return x.FileDeleteRequest
		}
	}
	return nil
}

func (x *HubMessage) GetUnregisterRequest() *UnregisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_UnregisterRequest); ok {
			return x.UnregisterRequest
		}
	}
	return nil
}

func (x *HubMessage) GetCertRenewResponse() *CertRenewResponse {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_CertRenewResponse); ok {
			return x.CertRenewResponse
		}
	}
	return nil
}

func (x *HubMessage) GetTerminalOpenRequest() *TerminalOpenRequest {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_TerminalOpenRequest); ok {
			return x.TerminalOpenRequest
		}
	}
	return nil
}

func (x *HubMessage) GetTerminalInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_TerminalInput); ok {
			return x.TerminalInput
		}
	}
	return nil
}

func (x *HubMessage) GetTerminalResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_TerminalResize); ok {
			return x.TerminalResize
		}
	}
	return nil
}

func (x *HubMessage) GetTerminalClose() *TerminalClose {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_TerminalClose); ok {
			return x.TerminalClose
		}
	}
	return nil
}

type isHubMessage_Payload interface {
	isHubMessage_Payload()
}

type HubMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,1,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type HubMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,2,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type HubMessage_FileListRequest struct {
	// Stubs for sub-projects 4-6
	FileListRequest *FileListRequest `protobuf:"bytes,10,opt,name=file_list_request,json=fileListRequest,proto3,oneof"`
}

type HubMessage_LogStreamRequest struct {
	LogStreamRequest *LogStreamRequest `protobuf:"bytes,11,opt,name=log_stream_request,json=logStreamRequest,proto3,oneof"`
}

type HubMessage_FileUploadRequest struct {
	FileUploadRequest *FileUploadRequest `protobuf:"bytes,12,opt,name=file_upload_request,json=fileUploadRequest,proto3,oneof"`
}

type HubMessage_FileReadRequest struct {
	FileReadRequest *FileReadRequest `protobuf:"bytes,13,opt,name=file_read_request,json=fileReadRequest,proto3,oneof"`
}

type HubMessage_LogStreamStop struct {
	LogStreamStop *LogStreamStop `protobuf:"bytes,14,opt,name=log_stream_stop,json=logStreamStop,proto3,oneof"`
}

type HubMessage_FileDeleteRequest struct {
	FileDeleteRequest *FileDeleteRequest `protobuf:"bytes,15,opt,name=file_delete_request,json=fileDeleteRequest,proto3,oneof"`
}

type HubMessage_UnregisterRequest struct {
	UnregisterRequest *UnregisterRequest `protobuf:"bytes,16,opt,name=unregister_request,json=unregisterRequest,proto3,oneof"`
}

type HubMessage_CertRenewResponse struct {
	CertRenewResponse *CertRenewResponse `protobuf:"bytes,17,opt,name=cert_renew_response,json=certRenewResponse,proto3,oneof"`
}

type HubMessage_TerminalOpenRequest struct {
	TerminalOpenRequest *TerminalOpenRequest `protobuf:"bytes,18,opt,name=terminal_open_request,json=terminalOpenRequest,proto3,oneof"`
}

type HubMessage_TerminalInput struct {
	TerminalInput *TerminalInput `protobuf:"bytes,19,opt,name=terminal_input,json=terminalInput,proto3,oneof"`
}

type HubMessage_TerminalResize struct {
	TerminalResize *TerminalResize `protobuf:"bytes,20,opt,name=terminal_resize,json=terminalResize,proto3,oneof"`
}

type HubMessage_TerminalClose struct {
	TerminalClose *TerminalClose `protobuf:"bytes,21,opt,name=terminal_close,json=terminalClose,proto3,oneof"`
}

func (*HubMessage_HeartbeatAck) isHubMessage_Payload() {}

func (*HubMessage_RegisterAck) isHubMessage_Payload() {}

func (*HubMessage_FileListRequest) isHubMessage_Payload() {}

func (*HubMessage_LogStreamRequest) isHubMessage_Payload() {}

func (*HubMessage_FileUploadRequest) isHubMessage_Payload() {}

func (*HubMessage_FileReadRequest) isHubMessage_Payload() {}

func (*HubMessage_LogStreamStop) isHubMessage_Payload() {}

func (*HubMessage_FileDeleteRequest) isHubMessage_Payload() {}

func (*HubMessage_UnregisterRequest) isHubMessage_Payload() {}

func (*HubMessage_CertRenewResponse) isHubMessage_Payload() {}

func (*HubMessage_TerminalOpenRequest) isHubMessage_Payload() {}

func (*HubMessage_TerminalInput) isHubMessage_Payload() {}

func (*HubMessage_TerminalResize) isHubMessage_Payload() {}

func (*HubMessage_TerminalClose) isHubMessage_Payload() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SystemInfo    *SystemInfo            `protobuf:"bytes,3,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *Heartbeat) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Csr           []byte                 `protobuf:"bytes,6,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgent.ProtoReflect.Descriptor instead.
func (*RegisterAgent) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterAgent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterAgent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterAgent) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterAgent) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ClientCert    []byte                 `protobuf:"bytes,4,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	CaCert        []byte                 `protobuf:"bytes,5,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAck) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RegisterAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterAck) GetClientCert() []byte {
	if x != nil {
		return x.ClientCert
	}
	return nil
}

func (x *RegisterAck) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,3,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SystemInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *SystemInfo) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *SystemInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// File browsing (sub-project 4)
type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FileListRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Files         []*FileNode            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *FileListResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileListResponse) GetFiles() []*FileNode {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Readable      bool                   `protobuf:"varint,5,opt,name=readable,proto3" json:"readable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileNode) Reset() {
	*x = FileNode{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNode) ProtoMessage() {}

func (x *FileNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNode.ProtoReflect.Descriptor instead.
func (*FileNode) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *FileNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileNode) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileNode) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileNode) GetReadable() bool {
	if x != nil {
		return x.Readable
	}
	return false
}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *FileReadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileReadRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *FileReadResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileReadResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileReadResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Log tailing (sub-project 5)
type LogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Grep          string                 `protobuf:"bytes,4,opt,name=grep,proto3" json:"grep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *LogStreamRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogStreamRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogStreamRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LogStreamRequest) GetGrep() string {
	if x != nil {
		return x.Grep
	}
	return ""
}

type LogStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamChunk) Reset() {
	*x = LogStreamChunk{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamChunk) ProtoMessage() {}

func (x *LogStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamChunk.ProtoReflect.Descriptor instead.
func (*LogStreamChunk) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *LogStreamChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogStreamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogStreamChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LogStreamStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamStop) Reset() {
	*x = LogStreamStop{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamStop) ProtoMessage() {}

func (x *LogStreamStop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamStop.ProtoReflect.Descriptor instead.
func (*LogStreamStop) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *LogStreamStop) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// File upload / Dropzone (sub-project 6)
type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *FileUploadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FileUploadRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type FileUploadAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadAck) Reset() {
	*x = FileUploadAck{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadAck) ProtoMessage() {}

func (x *FileUploadAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadAck.ProtoReflect.Descriptor instead.
func (*FileUploadAck) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *FileUploadAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileUploadAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileUploadAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// File deletion (dropzone)
type FileDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteRequest) Reset() {
	*x = FileDeleteRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteRequest) ProtoMessage() {}

func (x *FileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteRequest.ProtoReflect.Descriptor instead.
func (*FileDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *FileDeleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileDeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteResponse) Reset() {
	*x = FileDeleteResponse{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteResponse) ProtoMessage() {}

func (x *FileDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteResponse.ProtoReflect.Descriptor instead.
func (*FileDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FileDeleteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Server unregistration
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *UnregisterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UnregisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAck) Reset() {
	*x = UnregisterAck{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAck) ProtoMessage() {}

func (x *UnregisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAck.ProtoReflect.Descriptor instead.
func (*UnregisterAck) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *UnregisterAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UnregisterAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Certificate renewal (mTLS)
type CertRenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csr           []byte                 `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRenewRequest) Reset() {
	*x = CertRenewRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRenewRequest) ProtoMessage() {}

func (x *CertRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRenewRequest.ProtoReflect.Descriptor instead.
func (*CertRenewRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *CertRenewRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type CertRenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCert    []byte                 `protobuf:"bytes,1,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	CaCert        []byte                 `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRenewResponse) Reset() {
	*x = CertRenewResponse{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRenewResponse) ProtoMessage() {}

func (x *CertRenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRenewResponse.ProtoReflect.Descriptor instead.
func (*CertRenewResponse) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *CertRenewResponse) GetClientCert() []byte {
	if x != nil {
		return x.ClientCert
	}
	return nil
}

func (x *CertRenewResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *CertRenewResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Interactive terminal
type TerminalOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	RunAsUser     string                 `protobuf:"bytes,5,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOpenRequest) Reset() {
	*x = TerminalOpenRequest{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpenRequest) ProtoMessage() {}

func (x *TerminalOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpenRequest.ProtoReflect.Descriptor instead.
func (*TerminalOpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *TerminalOpenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOpenRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalOpenRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalOpenRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *TerminalOpenRequest) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

type TerminalOpenAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOpenAck) Reset() {
	*x = TerminalOpenAck{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpenAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpenAck) ProtoMessage() {}

func (x *TerminalOpenAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpenAck.ProtoReflect.Descriptor instead.
func (*TerminalOpenAck) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *TerminalOpenAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOpenAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TerminalOpenAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *TerminalResize) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalData) Reset() {
	*x = TerminalData{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalData) ProtoMessage() {}

func (x *TerminalData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalData.ProtoReflect.Descriptor instead.
func (*TerminalData) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{27}
}

func (x *TerminalData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalExit) Reset() {
	*x = TerminalExit{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalExit) ProtoMessage() {}

func (x *TerminalExit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalExit.ProtoReflect.Descriptor instead.
func (*TerminalExit) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{28}
}

func (x *TerminalExit) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TerminalExit) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TerminalClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalClose) Reset() {
	*x = TerminalClose{}
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalClose) ProtoMessage() {}

func (x *TerminalClose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aerodocs_v1_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalClose.ProtoReflect.Descriptor instead.
func (*TerminalClose) Descriptor() ([]byte, []int) {
	return file_proto_aerodocs_v1_agent_proto_rawDescGZIP(), []int{29}
}

func (x *TerminalClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_proto_aerodocs_v1_agent_proto protoreflect.FileDescriptor

const file_proto_aerodocs_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/aerodocs/v1/agent.proto\x12\vaerodocs.v1\"\xf1\x06\n" +
	"\fAgentMessage\x126\n" +
	"\theartbeat\x18\x01 \x01(\v2\x16.aerodocs.v1.HeartbeatH\x00R\theartbeat\x128\n" +
	"\bregister\x18\x02 \x01(\v2\x1a.aerodocs.v1.RegisterAgentH\x00R\bregister\x12M\n" +
	"\x12file_list_response\x18\n" +
	" \x01(\v2\x1d.aerodocs.v1.FileListResponseH\x00R\x10fileListResponse\x12G\n" +
	"\x10log_stream_chunk\x18\v \x01(\v2\x1b.aerodocs.v1.LogStreamChunkH\x00R\x0elogStreamChunk\x12D\n" +
	"\x0ffile_upload_ack\x18\f \x01(\v2\x1a.aerodocs.v1.FileUploadAckH\x00R\rfileUploadAck\x12M\n" +
	"\x12file_read_response\x18\r \x01(\v2\x1d.aerodocs.v1.FileReadResponseH\x00R\x10fileReadResponse\x12S\n" +
	"\x14file_delete_response\x18\x0f \x01(\v2\x1f.aerodocs.v1.FileDeleteResponseH\x00R\x12fileDeleteResponse\x12C\n" +
	"\x0eunregister_ack\x18\x10 \x01(\v2\x1a.aerodocs.v1.UnregisterAckH\x00R\runregisterAck\x12M\n" +
	"\x12cert_renew_request\x18\x11 \x01(\v2\x1d.aerodocs.v1.CertRenewRequestH\x00R\x10certRenewRequest\x12J\n" +
	"\x11terminal_open_ack\x18\x12 \x01(\v2\x1c.aerodocs.v1.TerminalOpenAckH\x00R\x0fterminalOpenAck\x12@\n" +
	"\rterminal_data\x18\x13 \x01(\v2\x19.aerodocs.v1.TerminalDataH\x00R\fterminalData\x12@\n" +
	"\rterminal_exit\x18\x14 \x01(\v2\x19.aerodocs.v1.TerminalExitH\x00R\fterminalExitB\t\n" +
	"\apayload\"\xb6\b\n" +
	"\n" +
	"HubMessage\x12@\n" +
	"\rheartbeat_ack\x18\x01 \x01(\v2\x19.aerodocs.v1.HeartbeatAckH\x00R\fheartbeatAck\x12=\n" +
	"\fregister_ack\x18\x02 \x01(\v2\x18.aerodocs.v1.RegisterAckH\x00R\vregisterAck\x12J\n" +
	"\x11file_list_request\x18\n" +
	" \x01(\v2\x1c.aerodocs.v1.FileListRequestH\x00R\x0ffileListRequest\x12M\n" +
	"\x12log_stream_request\x18\v \x01(\v2\x1d.aerodocs.v1.LogStreamRequestH\x00R\x10logStreamRequest\x12P\n" +
	"\x13file_upload_request\x18\f \x01(\v2\x1e.aerodocs.v1.FileUploadRequestH\x00R\x11fileUploadRequest\x12J\n" +
	"\x11file_read_request\x18\r \x01(\v2\x1c.aerodocs.v1.FileReadRequestH\x00R\x0ffileReadRequest\x12D\n" +
	"\x0flog_stream_stop\x18\x0e \x01(\v2\x1a.aerodocs.v1.LogStreamStopH\x00R\rlogStreamStop\x12P\n" +
	"\x13file_delete_request\x18\x0f \x01(\v2\x1e.aerodocs.v1.FileDeleteRequestH\x00R\x11fileDeleteRequest\x12O\n" +
	"\x12unregister_request\x18\x10 \x01(\v2\x1e.aerodocs.v1.UnregisterRequestH\x00R\x11unregisterRequest\x12P\n" +
	"\x13cert_renew_response\x18\x11 \x01(\v2\x1e.aerodocs.v1.CertRenewResponseH\x00R\x11certRenewResponse\x12V\n" +
	"\x15terminal_open_request\x18\x12 \x01(\v2 .aerodocs.v1.TerminalOpenRequestH\x00R\x13terminalOpenRequest\x12C\n" +
	"\x0eterminal_input\x18\x13 \x01(\v2\x1a.aerodocs.v1.TerminalInputH\x00R\rterminalInput\x12F\n" +
	"\x0fterminal_resize\x18\x14 \x01(\v2\x1b.aerodocs.v1.TerminalResizeH\x00R\x0eterminalResize\x12C\n" +
	"\x0eterminal_close\x18\x15 \x01(\v2\x1a.aerodocs.v1.TerminalCloseH\x00R\rterminalCloseB\t\n" +
	"\apayload\"\x9f\x01\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x128\n" +
	"\vsystem_info\x18\x03 \x01(\v2\x17.aerodocs.v1.SystemInfoR\n" +
	"systemInfo\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\",\n" +
	"\fHeartbeatAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xa7\x01\n" +
	"\rRegisterAgent\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x10\n" +
	"\x03csr\x18\x06 \x01(\fR\x03csr\"\x94\x01\n" +
	"\vRegisterAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vclient_cert\x18\x04 \x01(\fR\n" +
	"clientCert\x12\x17\n" +
	"\aca_cert\x18\x05 \x01(\fR\x06caCert\"\x9e\x01\n" +
	"\n" +
	"SystemInfo\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x03 \x01(\x01R\vdiskPercent\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"D\n" +
	"\x0fFileListRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"t\n" +
	"\x10FileListResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x05files\x18\x02 \x03(\v2\x15.aerodocs.v1.FileNodeR\x05files\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"y\n" +
	"\bFileNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\breadable\x18\x05 \x01(\bR\breadable\"r\n" +
	"\x0fFileReadRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"\x97\x01\n" +
	"\x10FileReadResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"q\n" +
	"\x10LogStreamRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04grep\x18\x04 \x01(\tR\x04grep\"[\n" +
	"\x0eLogStreamChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\".\n" +
	"\rLogStreamStop\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"x\n" +
	"\x11FileUploadRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"^\n" +
	"\rFileUploadAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"F\n" +
	"\x11FileDeleteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"c\n" +
	"\x12FileDeleteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"2\n" +
	"\x11UnregisterRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"^\n" +
	"\rUnregisterAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"$\n" +
	"\x10CertRenewRequest\x12\x10\n" +
	"\x03csr\x18\x01 \x01(\fR\x03csr\"c\n" +
	"\x11CertRenewResponse\x12\x1f\n" +
	"\vclient_cert\x18\x01 \x01(\fR\n" +
	"clientCert\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\fR\x06caCert\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8e\x01\n" +
	"\x13TerminalOpenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x1e\n" +
	"\vrun_as_user\x18\x05 \x01(\tR\trunAsUser\"`\n" +
	"\x0fTerminalOpenAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"B\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"W\n" +
	"\x0eTerminalResize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"A\n" +
	"\fTerminalData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"`\n" +
	"\fTerminalExit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\".\n" +
	"\rTerminalClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId2Q\n" +
	"\fAgentService\x12A\n" +
	"\aConnect\x12\x19.aerodocs.v1.AgentMessage\x1a\x17.aerodocs.v1.HubMessage(\x010\x01B,Z*github.com/wyiu/aerodocs/proto/aerodocs/v1b\x06proto3"

var (
	file_proto_aerodocs_v1_agent_proto_rawDescOnce sync.Once
	file_proto_aerodocs_v1_agent_proto_rawDescData []byte
)

func file_proto_aerodocs_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_aerodocs_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_aerodocs_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aerodocs_v1_agent_proto_rawDesc), len(file_proto_aerodocs_v1_agent_proto_rawDesc)))
	})
	return file_proto_aerodocs_v1_agent_proto_rawDescData
}

var file_proto_aerodocs_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_aerodocs_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),        // 0: aerodocs.v1.AgentMessage
	(*HubMessage)(nil),          // 1: aerodocs.v1.HubMessage
	(*Heartbeat)(nil),           // 2: aerodocs.v1.Heartbeat
	(*HeartbeatAck)(nil),        // 3: aerodocs.v1.HeartbeatAck
	(*RegisterAgent)(nil),       // 4: aerodocs.v1.RegisterAgent
	(*RegisterAck)(nil),         // 5: aerodocs.v1.RegisterAck
	(*SystemInfo)(nil),          // 6: aerodocs.v1.SystemInfo
	(*FileListRequest)(nil),     // 7: aerodocs.v1.FileListRequest
	(*FileListResponse)(nil),    // 8: aerodocs.v1.FileListResponse
	(*FileNode)(nil),            // 9: aerodocs.v1.FileNode
	(*FileReadRequest)(nil),     // 10: aerodocs.v1.FileReadRequest
	(*FileReadResponse)(nil),    // 11: aerodocs.v1.FileReadResponse
	(*LogStreamRequest)(nil),    // 12: aerodocs.v1.LogStreamRequest
	(*LogStreamChunk)(nil),      // 13: aerodocs.v1.LogStreamChunk
	(*LogStreamStop)(nil),       // 14: aerodocs.v1.LogStreamStop
	(*FileUploadRequest)(nil),   // 15: aerodocs.v1.FileUploadRequest
	(*FileUploadAck)(nil),       // 16: aerodocs.v1.FileUploadAck
	(*FileDeleteRequest)(nil),   // 17: aerodocs.v1.FileDeleteRequest
	(*FileDeleteResponse)(nil),  // 18: aerodocs.v1.FileDeleteResponse
	(*UnregisterRequest)(nil),   // 19: aerodocs.v1.UnregisterRequest
	(*UnregisterAck)(nil),       // 20: aerodocs.v1.UnregisterAck
	(*CertRenewRequest)(nil),    // 21: aerodocs.v1.CertRenewRequest
	(*CertRenewResponse)(nil),   // 22: aerodocs.v1.CertRenewResponse
	(*TerminalOpenRequest)(nil), // 23: aerodocs.v1.TerminalOpenRequest
	(*TerminalOpenAck)(nil),     // 24: aerodocs.v1.TerminalOpenAck
	(*TerminalInput)(nil),       // 25: aerodocs.v1.TerminalInput
	(*TerminalResize)(nil),      // 26: aerodocs.v1.TerminalResize
	(*TerminalData)(nil),        // 27: aerodocs.v1.TerminalData
	(*TerminalExit)(nil),        // 28: aerodocs.v1.TerminalExit
	(*TerminalClose)(nil),       // 29: aerodocs.v1.TerminalClose
}
var file_proto_aerodocs_v1_agent_proto_depIdxs = []int32{
	2,  // 0: aerodocs.v1.AgentMessage.heartbeat:type_name -> aerodocs.v1.Heartbeat
	4,  // 1: aerodocs.v1.AgentMessage.register:type_name -> aerodocs.v1.RegisterAgent
	8,  // 2: aerodocs.v1.AgentMessage.file_list_response:type_name -> aerodocs.v1.FileListResponse
	13, // 3: aerodocs.v1.AgentMessage.log_stream_chunk:type_name -> aerodocs.v1.LogStreamChunk
	16, // 4: aerodocs.v1.AgentMessage.file_upload_ack:type_name -> aerodocs.v1.FileUploadAck
	11, // 5: aerodocs.v1.AgentMessage.file_read_response:type_name -> aerodocs.v1.FileReadResponse
	18, // 6: aerodocs.v1.AgentMessage.file_delete_response:type_name -> aerodocs.v1.FileDeleteResponse
	20, // 7: aerodocs.v1.AgentMessage.unregister_ack:type_name -> aerodocs.v1.UnregisterAck
	21, // 8: aerodocs.v1.AgentMessage.cert_renew_request:type_name -> aerodocs.v1.CertRenewRequest
	24, // 9: aerodocs.v1.AgentMessage.terminal_open_ack:type_name -> aerodocs.v1.TerminalOpenAck
	27, // 10: aerodocs.v1.AgentMessage.terminal_data:type_name -> aerodocs.v1.TerminalData
	28, // 11: aerodocs.v1.AgentMessage.terminal_exit:type_name -> aerodocs.v1.TerminalExit
	3,  // 12: aerodocs.v1.HubMessage.heartbeat_ack:type_name -> aerodocs.v1.HeartbeatAck
	5,  // 13: aerodocs.v1.HubMessage.register_ack:type_name -> aerodocs.v1.RegisterAck
	7,  // 14: aerodocs.v1.HubMessage.file_list_request:type_name -> aerodocs.v1.FileListRequest
	12, // 15: aerodocs.v1.HubMessage.log_stream_request:type_name -> aerodocs.v1.LogStreamRequest
	15, // 16: aerodocs.v1.HubMessage.file_upload_request:type_name -> aerodocs.v1.FileUploadRequest
	10, // 17: aerodocs.v1.HubMessage.file_read_request:type_name -> aerodocs.v1.FileReadRequest
	14, // 18: aerodocs.v1.HubMessage.log_stream_stop:type_name -> aerodocs.v1.LogStreamStop
	17, // 19: aerodocs.v1.HubMessage.file_delete_request:type_name -> aerodocs.v1.FileDeleteRequest
	19, // 20: aerodocs.v1.HubMessage.unregister_request:type_name -> aerodocs.v1.UnregisterRequest
	22, // 21: aerodocs.v1.HubMessage.cert_renew_response:type_name -> aerodocs.v1.CertRenewResponse
	23, // 22: aerodocs.v1.HubMessage.terminal_open_request:type_name -> aerodocs.v1.TerminalOpenRequest
	25, // 23: aerodocs.v1.HubMessage.terminal_input:type_name -> aerodocs.v1.TerminalInput
	26, // 24: aerodocs.v1.HubMessage.terminal_resize:type_name -> aerodocs.v1.TerminalResize
	29, // 25: aerodocs.v1.HubMessage.terminal_close:type_name -> aerodocs.v1.TerminalClose
	6,  // 26: aerodocs.v1.Heartbeat.system_info:type_name -> aerodocs.v1.SystemInfo
	9,  // 27: aerodocs.v1.FileListResponse.files:type_name -> aerodocs.v1.FileNode
	0,  // 28: aerodocs.v1.AgentService.Connect:input_type -> aerodocs.v1.AgentMessage
	1,  // 29: aerodocs.v1.AgentService.Connect:output_type -> aerodocs.v1.HubMessage
	29, // [29:30] is the sub-list for method output_type
	28, // [28:29] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_aerodocs_v1_agent_proto_init() }
func file_proto_aerodocs_v1_agent_proto_init() {
	if File_proto_aerodocs_v1_agent_proto != nil {
		return
	}
	file_proto_aerodocs_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Register)(nil),
		(*AgentMessage_FileListResponse)(nil),
		(*AgentMessage_LogStreamChunk)(nil),
		(*AgentMessage_FileUploadAck)(nil),
		(*AgentMessage_FileReadResponse)(nil),
		(*AgentMessage_FileDeleteResponse)(nil),
		(*AgentMessage_UnregisterAck)(nil),
		(*AgentMessage_CertRenewRequest)(nil),
		(*AgentMessage_TerminalOpenAck)(nil),
		(*AgentMessage_TerminalData)(nil),
		(*AgentMessage_TerminalExit)(nil),
	}
	file_proto_aerodocs_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*HubMessage_HeartbeatAck)(nil),
		(*HubMessage_RegisterAck)(nil),
		(*HubMessage_FileListRequest)(nil),
		(*HubMessage_LogStreamRequest)(nil),
		(*HubMessage_FileUploadRequest)(nil),
		(*HubMessage_FileReadRequest)(nil),
		(*HubMessage_LogStreamStop)(nil),
		(*HubMessage_FileDeleteRequest)(nil),
		(*HubMessage_UnregisterRequest)(nil),
		(*HubMessage_CertRenewResponse)(nil),
		(*HubMessage_TerminalOpenRequest)(nil),
		(*HubMessage_TerminalInput)(nil),
		(*HubMessage_TerminalResize)(nil),
		(*HubMessage_TerminalClose)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aerodocs_v1_agent_proto_rawDesc), len(file_proto_aerodocs_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aerodocs_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_aerodocs_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_aerodocs_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_aerodocs_v1_agent_proto = out.File
	file_proto_aerodocs_v1_agent_proto_goTypes = nil
	file_proto_aerodocs_v1_agent_proto_depIdxs = nil
}
